-- Admin regulations watcher
-- Service-role only tables. Admin pages + cron routes access via supabaseAdmin().

create table if not exists public.regulation_sources (
  id bigint generated by default as identity primary key,
  key text not null unique,
  title text not null,
  url text not null,
  source_group text not null default 'general',
  selector text,
  status text not null default 'active'
    check (status in ('active', 'paused', 'error')),
  last_hash text,
  last_checked_at timestamptz,
  last_changed_at timestamptz,
  last_error text,
  latest_excerpt text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.regulation_source_snapshots (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.regulation_sources(id) on delete cascade,
  content_hash text not null,
  content_text text not null default '',
  excerpt text,
  changed boolean not null default true,
  fetched_at timestamptz not null default now(),
  unique (source_id, content_hash)
);

create index if not exists regulation_sources_status_idx
  on public.regulation_sources(status, source_group);

create index if not exists regulation_sources_last_checked_idx
  on public.regulation_sources(last_checked_at desc);

create index if not exists regulation_source_snapshots_source_idx
  on public.regulation_source_snapshots(source_id, fetched_at desc);

alter table public.regulation_sources enable row level security;
alter table public.regulation_source_snapshots enable row level security;

-- No policies on purpose: only service-role server code should access these tables.

insert into public.regulation_sources
  (key, title, url, source_group, selector, notes)
values
  (
    'ge-fire-regulation',
    'სახანძრო უსაფრთხოების ტექნიკური რეგლამენტი',
    'https://matsne.gov.ge/',
    'Georgia',
    null,
    'Seed source. Replace with exact matsne document URL after legal shortlist is confirmed.'
  ),
  (
    'ge-building-regulation',
    'სამშენებლო უსაფრთხოების ტექნიკური რეგლამენტი',
    'https://matsne.gov.ge/',
    'Georgia',
    null,
    'Seed source. Replace with exact matsne document URL after legal shortlist is confirmed.'
  ),
  (
    'en-12101-6',
    'EN 12101-6 reference page',
    'https://www.en-standard.eu/bs-en-12101-6-2022',
    'Fire safety',
    null,
    'Smoke control / pressurization reference'
  ),
  (
    'nfpa-92',
    'NFPA 92 standard page',
    'https://www.nfpa.org/codes-and-standards/all-codes-and-standards/list-of-codes-and-standards/detail?code=92',
    'Fire safety',
    null,
    'Smoke control reference'
  ),
  (
    'ashrae-62-1',
    'ASHRAE 62.1 / 62.2 standards',
    'https://www.ashrae.org/technical-resources/bookstore/standards-62-1-62-2',
    'HVAC',
    null,
    'Ventilation / IAQ reference'
  )
on conflict (key) do nothing;
