-- engineers.ge · hero ad payments ledger
-- Admin-only invoice/payment tracking for homepage hero ad slots.

create table if not exists public.hero_ad_payments (
  id bigint generated by default as identity primary key,
  slot_key text not null references public.hero_ad_slots(slot_key) on delete cascade,
  client_name text not null default '',
  invoice_no text not null default '',
  amount_gel numeric(10,2) not null default 0 check (amount_gel >= 0),
  status text not null default 'sent'
    check (status in ('draft', 'sent', 'paid', 'cancelled')),
  period_start date,
  period_end date,
  due_date date,
  paid_at date,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists hero_ad_payments_slot_key_idx
  on public.hero_ad_payments(slot_key, created_at desc);

create index if not exists hero_ad_payments_status_idx
  on public.hero_ad_payments(status, due_date asc);

alter table public.hero_ad_payments enable row level security;

-- No public policies on purpose: admin/service-role only finance data.
