-- engineers.ge · hero ad upload requests
-- Public `/ads` upload requests reviewed by admin before publishing to a slot.

create table if not exists public.hero_ad_upload_requests (
  id bigint generated by default as identity primary key,
  slot_key text not null references public.hero_ad_slots(slot_key) on delete cascade,
  company_name text not null default '',
  contact_name text not null default '',
  contact_email text not null default '',
  contact_phone text not null default '',
  note text not null default '',
  asset_url text not null default '',
  asset_path text not null default '',
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  review_note text not null default '',
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists hero_ad_upload_requests_status_idx
  on public.hero_ad_upload_requests(status, created_at desc);

create index if not exists hero_ad_upload_requests_slot_idx
  on public.hero_ad_upload_requests(slot_key, created_at desc);

alter table public.hero_ad_upload_requests enable row level security;

-- Public writes go only through server route; no direct policies on purpose.
